### ISSUE TITLE
Experimental inbody tag works almost all the time; hide the _container element programatically also works

### ISSUE THREAD

**Issue by vinerz** [cbalit/re-captcha#12]
Hello everyone! I am also struggling with the fact that for some obscure reason recaptcha.js API doesn't deal with direct DOM references and uses some weird old school query selectors. Dealing with this nightmare of the eternal spinning wheel, I stumbled upon this component.

I gave a try and used the new `inbody` flag.
It works almost all the times on Chrome and Safari, despite some weird positioning situations (Chrome is failing to get the first `getBoundingClientRect` and gives up sometimes).

With that, when I don't need the Recaptcha on its place, I simply do a `this.$.recaptcha._container.style.display` set to `none` and it surprisingly works!

Maybe we can add the methods `hide()` and `show()` and deal internally with the container that gets attached to the body without the hassle to write this complex and long line of HTML Styling.

**Comment by vinerz** [comment]
Update: It seems that the recaptcha is only rendered wrong when the first paint of the parent element happens when `window` is a bit scrolled

**Comment by tobilen** [comment]
@vinerz  did you try the 2.0 preview branch? i encountered a similiar issue and created a PR https://github.com/cbalit/re-captcha/pull/11

might fix the issue for you

**Comment by vinerz** [comment]
Hey @tobilen! I just tried adding the `document.body.scrollTop` to the rect and it works flawlessy.

Also, adding a check if the `_container.querySelector('div')` exists made possible to prevent the first paint error that I was getting before.

I tried to install the preview branch but the newer bower requirements broke my dependency tree.
