### ISSUE TITLE
 <google-recaptcha> is not working for me in chrome. same code is working fine in IE +  firefox + safari.  getting  Error : "Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame""

### ISSUE THREAD

**Issue by vyomabypt** [cbalit/re-captcha#17]
Hi,

Here, i have uploaded my source code.

i have written captcha code in my-samplepage.html. 

That same code is working fine in IE + Firefox + safari but getting below error in chrome.

```
Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at lb.t.tZ (https://www.gstatic.com/recaptcha/api2/v1548052318968/recaptcha__en.js:515:271)
    at yj (https://www.gstatic.com/recaptcha/api2/v1548052318968/recaptcha__en.js:522:135)
    at Object.init (https://www.gstatic.com/recaptcha/api2/v1548052318968/recaptcha__en.js:527:434)
    at https://www.google.com/recaptcha/api2/bframe?hl=en&v=v1548052318968&k=6LcI04UUAAAAADBTEtJ0exAwAe57vkNqObj6tKIQ&cb=r1oyt78mj7bb:184:30
```

[firstdemo.zip](https://github.com/cbalit/re-captcha/files/2821304/firstdemo.zip)

Could you please assist me here?

Thanks in Advanced!

**Comment by cbalit** [comment]
Hello,

I just have a look to your source code in my-samplepage.html.
You are using google-recaptcha element (from https://github.com/Zecat/google-recaptcha)
where I realize you also post the issue. Can we close this one ?

**Comment by tvvignesh** [comment]
@cbalit I am facing this issue but in re-captcha. After some googling, found this blog which states the reason for the issue: https://medium.com/@tomas_26986/using-recaptcha-with-react-and-shadow-dom-abfd19fa03a

I am using re-captcha within lit-elements and I get this error. Any idea on how we can fix this in re-captcha ?

**Comment by cbalit** [comment]
Hi,

Salut Cyril,

You point a issue due to the behavior of re-captcha versus shadow dom. For
now i doesn't have the solution but i worked with a colleague and we are
about to release a new version that doesn't use the shadow dom. If you
wan't i can give you a sign when the version is ready.

Cyril

Le sam. 18 janv. 2020 à 16:44, T.V.VIGNESH <notifications@github.com> a
écrit :

**Comment by shikanime** [comment]
Hi @tvvignesh, I'm not 100% sure but from what I remembered and my understanding – reCaptcha is using iframes and have some trouble with the browser context in the shadownDOM (https://github.com/whatwg/html/issues/763)

On this re-capcha component I doesn't use shadownDOM for the same reason. On the article the components is rendered outside the shadownDOM then "moved?" using ReactPortal.

Maybe Polymer 1 is using shadownDOM 🤷  

Correct me if I'm wrong 🚩
