### ISSUE TITLE
,

### ISSUE THREAD

**Issue by ghost** [cbalit/re-captcha#3]
,

**Comment by cbalit** [comment]
@triune , it'a nice feature to have. I add a reload function on the component. You'll find a demoLang.html that use it. Is it ok for you ?

**Comment by triune** [comment]
@cbalit it works **beautifully**! Thank you for granting the component i18n :)

The only problem now is that I cannot pull your component in via bower (git only), it keeps grabbing the google-recaptcha component instead. I'm sure you'll sort this out eventually however as the dust is still settling from the retirement of that other package.

**Comment by cbalit** [comment]
@triune i'll try to make a new release this week.

**Comment by cbalit** [comment]
@triune you can now use the v1.1.1 version

**Comment by triune** [comment]
@cbalit, brilliant... cheers!
