### ISSUE TITLE
Remove Unnecessary Dependencies From bower.json

### ISSUE THREAD

**Issue by idoshamun** [cbalit/re-captcha#7]
The only dependency needed in my opinion is polymer and the other ones are for demo purposes.
Please update bower.json accordingly.

**Comment by cbalit** [comment]
In the last release the only dependency is polymer. The others are devDependencies needed for development and test.

**Comment by idoshamun** [comment]
For some reason when I used `bower` it has installed everything...
I have to check closer.

**Comment by cbalit** [comment]
Maybe you are using a previous version. We remove dependencies in 1.1.1 version.

**Comment by idoshamun** [comment]
Actually take a look at the `bower.json` file in the latest release/tag (v1.1.1), they are still there.
https://github.com/cbalit/re-captcha/blob/v1.1.1/bower.json#L14

**Comment by cbalit** [comment]
You're completely right. We removed the dependencies in the master and didn't release it.  I 've just released a v1.1.2 tag for this purpose.

**Comment by idoshamun** [comment]
Thanks!
